### ISSUE TITLE
Error fetching embedded sass protocol beta 17

### ISSUE THREAD

**Issue by datapolitical** [ntkme/sass-embedded-host-ruby#12]
ERROR:  Error fetching https://raw.githubusercontent.com/sass/embedded-protocol/1.0.0-beta.17/embedded_sass.proto:
/Users/chris/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/open-uri.rb:387:in `open_http': 404 Not Found (OpenURI::HTTPError)
	from /Users/chris/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/open-uri.rb:764:in `buffer_open'
	from /Users/chris/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/open-uri.rb:235:in `block in open_loop'
	from /Users/chris/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/open-uri.rb:233:in `catch'
	from /Users/chris/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/open-uri.rb:233:in `open_loop'
	from /Users/chris/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/open-uri.rb:174:in `open_uri'
	from /Users/chris/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/open-uri.rb:744:in `open'
	from extconf.rb:64:in `fetch'
	from extconf.rb:46:in `fetch_with_config'
	from extconf.rb:36:in `initialize'
	from extconf.rb:224:in `new'
	from extconf.rb:224:in `<main>'
curl -fsSLo /Users/chris/.rvm/gems/ruby-2.7.0/gems/sass-embedded-0.9.3/ext/sass/embedded_sass.proto -- https://raw.githubusercontent.com/sass/embedded-protocol/1.0.0-beta.17/embedded_sass.proto
make: *** [embedded_sass.proto] Error 1

**Comment by ntkme** [comment]
https://github.com/sass/embedded-protocol/issues/88

**Comment by ntkme** [comment]
Should have been fixed by upstream.
