### ISSUE TITLE
Failed to install on Github Actions after bundle update from 1.5x to 1.62

### ISSUE THREAD

**Issue by januszm** [ntkme/sass-embedded-host-ruby#121]
After last `bundle update` and update `sass-embedded` and `sassc-embedded` in one of my projects as below, Github Actions is unable to install gem and CI is not working

```
# Gemfile.lock diff
-    sass-embedded (1.56.1)
+    sass-embedded (1.62.1)
      google-protobuf (~> 3.21)
      rake (>= 10.0.0)
-    sassc-embedded (1.54.0)
-      sass-embedded (~> 1.54)
+    sass-embedded (1.62.1-x86_64-darwin)
+      google-protobuf (~> 3.21)
+    sass-embedded (1.62.1-x86_64-linux-gnu)
+      google-protobuf (~> 3.21)
+    sassc-embedded (1.59.0)
+      sass-embedded (~> 1.59)
```

```
Your bundle is locked to sass-embedded (1.62.1-x86_64-linux) from rubygems
repository https://rubygems.org/ or installed locally, but that version can no
longer be found in that source. That means the author of sass-embedded
```

no matter if I `bundle lock` with platform   x86_64-linux or x86_64-linux-gnu
but it looks like this version is available at rubygems (?!) https://rubygems.org/gems/sass-embedded/versions/1.62.1-x86_64-linux-gnu. Or is this some kind of mismatch between how Github defines the platform and how it is being released to rubygems (notice: linux vs linux-gnu)

**Comment by ntkme** [comment]
Likely a duplicate of https://github.com/ntkme/sass-embedded-host-ruby/issues/88

There error is known to happen if your rubygems version in the second installation is older than the version used in the first version.

**Comment by ntkme** [comment]
Please make sure you have rubygems >=3.3.22 and bundler >=2.3.22 all the time if you want to install Linux platform specific gems.

**Comment by januszm** [comment]
Gotcha, thank you. Now I'm getting `sass-embedded-1.62.1-x86_64-linux requires rubygems version >= 3.3.22, which is incompatible with the current version, 3.2.33`. I'll close this issue and try telling GH Actions to use newer Rubygems
