### ISSUE TITLE
Fails to install "jekyll" & "github-pages" with v1.63.1 

### ISSUE THREAD

**Issue by samruddhikhandale** [ntkme/sass-embedded-host-ruby#130]
Hi 👋 

I am unable to install "jekyll" & "github-pages" gems after the release of `v1.63.1`, wondering if it's a regression in latest releases.

Error message 👇 

> "sass" from sass conflicts with installed executable from sass-embedded

- Bundler version: v2.4.14
- Ruby version: v3.2

Temporary workaround: `gem install sass-embedded -v 1.62.1` followed by `gem install jekyll github-pages` works fine.

**Comment by ntkme** [comment]
From `1.63.1` onward, `sass-embedded` now provides a native Dart `sass` command in additional to the Ruby API. The old Ruby `sass` gem provides a pure Ruby `sass` command and Ruby API.

As for github-pages gem and jekyll gem, none of them would use the `sass` command. They only use the old Ruby API and new Ruby API respectively so it does not matter how do you deal with the conflict. - Overwriting one of the them will let it go through.

E.g.

``` sh
gem install sass
gem install sass-embedded --force
```

**Comment by ntkme** [comment]
The original Ruby `sass` gem reached end-of-life on 4 April 2019: https://sass-lang.com/blog/ruby-sass-is-unsupported

`github-pages` is a locked down environment with obsoleted dependencies, for which I can do nothing about: 
https://github.com/jekyll/jekyll/pull/8939#issuecomment-1541488479
