### ISSUE TITLE
Upgrading sass-embedded from 1.62.1 to 1.63.x causes tooling to generate wrong RBI for Sass::EmbeddedProtocol::Value::ArgumentList

### ISSUE THREAD

**Issue by MaximusMark** [ntkme/sass-embedded-host-ruby#132]
Might be an upstream issue but wanted to start here...

In my gemfile.lock:
```
    sass-embedded (1.63.4-x86_64-darwin)
      google-protobuf (~> 3.23)
```
`Using google-protobuf 3.23.3 (x86_64-darwin)`

After running `bin/tapioca dsl Sass::EmbeddedProtocol::Value::ArgumentList`
Generated sorbet/rbi/dsl/sass/embedded_protocol/value/argument_list.rbi:
```ruby
# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Sass::EmbeddedProtocol::Value::ArgumentList`.
# Please instead update this file by running `bin/tapioca dsl Sass::EmbeddedProtocol::Value::ArgumentList`.

class Sass::EmbeddedProtocol::Value::ArgumentList
...
  sig { returns(Google::Protobuf::RepeatedField[]) }
  def keywords; end
...
end
```
output of `srb tc`:
```
sorbet/rbi/dsl/sass/embedded_protocol/value/argument_list.rbi:45: Wrong number of type parameters for Google::Protobuf::RepeatedField. Expected: 1, got: 0 https://srb.help/7010
    45 |  sig { params(value: Google::Protobuf::RepeatedField[]).void }
```

Previous gemfile.lock:
```
    sass-embedded (1.62.1-x86_64-darwin)
      google-protobuf (~> 3.21)
```      
`Using google-protobuf 3.23.3 (x86_64-darwin)` (forced it to this version to narrow down the issue)

RBI signature (having correct Map type for value):
```
  sig { params(value: Google::Protobuf::Map[String, Sass::EmbeddedProtocol::Value]).void }
  def keywords=(value); end
```

Output of `srb tc`:
`No errors! Great job.`

**Comment by ntkme** [comment]
This class is generated by protobuf compiler `protoc` that I have no control at all. You should report it to upstream.

In practice this shouldn't matter, because for this package `Sass::EmbeddedProtocol` is a `private_constant` that user should never touch. This gem has [a conversion logic](https://github.com/ntkme/sass-embedded-host-ruby/blob/main/lib/sass/embedded/host/value_protofier.rb) between this internal format and user facing format so that end users would only use the public `Sass::Value`.

**Comment by ntkme** [comment]
By the way, this change in `protoc` 23.3 might be related: https://github.com/protocolbuffers/protobuf/commit/bd52d0483987f1a5186fc3daa261d1d76a787bcf

**Comment by ntkme** [comment]
You can try download the proto definition here: https://github.com/sass/sass/blob/main/spec/embedded_sass.proto

Try compile it to ruby code with protoc v21 and v23, and see if the generated code has any difference for RBI.
