### ISSUE TITLE
Unable to deploy on systems using x86_64-linux

### ISSUE THREAD

**Issue by shaneshort** [ntkme/sass-embedded-host-ruby#158]
Hi There,

I've recently pulled this library in as a dependency of jekyl and I'm having some issues with it on our platform. Specifically I can't see a build being made available for x86_64-linux, which causes the following problem for us whilst trying to run our pipelines:

```
Your bundle is locked to sass-embedded (1.68.0-x86_64-linux) from rubygems
repository https://rubygems.org/ or installed locally, but that version can no
longer be found in that source. That means the author of sass-embedded
(1.68.0-x86_64-linux) has removed it. You'll need to update your bundle to a
version other than sass-embedded (1.68.0-x86_64-linux) that hasn't been removed
in order to install.
```

I've attempted to add the 32 bit platform but that doesn't seem to help. Can we extend the release pipeline to target x86_64-linux also?

**Comment by ntkme** [comment]
This is a known bug in older version of bundler/rubygems. The minimum require version is rubygems >=3.3.22 and bundler >=2.3.22.

Please upgrade rubygems, then delete and recreate `Gemfile.lock`.

See #88 for more details.

**Comment by pat-s** [comment]
Ahh .22, I saw .2 in my head. Sorry for the noise!
