### ISSUE TITLE
1.54.0 can not be installed to M1 Mac

### ISSUE THREAD

**Issue by scivola** [ntkme/sass-embedded-host-ruby#50]
production: 

```terminal
gem i sass-embedded -v "1.54.0"
```

It fails:

```terminal
Gem::RemoteFetcher::FetchError: bad response Not Found 404 (https://github.com/sass/dart-sass-embedded/releases/download/1.54.0/sass_embedded-1.54.0-macos-arm64.tar.gz)
```

because `sass_embedded-1.54.0-macos-arm64.tar.gz` is not provided at
https://github.com/sass/dart-sass-embedded/releases/tag/1.54.0

**Comment by ntkme** [comment]
This is an upstream issue that dart-sass-embedded CI/CD pipeline is broken.

Right now you can force it to install the x64 version and run with rosetta before the issue is fixed in upstream: 

``` sh
gem install sass-embedded -- SASS_EMBEDDED=https://github.com/sass/dart-sass-embedded/releases/download/1.54.0/sass_embedded-1.54.0-macos-x64.tar.gz
```

Or, for `bundle`:

``` sh
bundle config build.sass-embedded SASS_EMBEDDED=https://github.com/sass/dart-sass-embedded/releases/download/1.54.0/sass_embedded-1.54.0-macos-x64.tar.gz
bundle install
```

**Comment by scivola** [comment]
Thank you for the advice.

Do you have any idea to improve error message when download fails?
If no, please close this issue.

日本語で失礼します。英語が下手すぎて伝わらなさそうなので・・・
（読むほうはいけますのでもしリプライいただくなら英語で大丈夫です）
なにげに `gem up sass-embedded` したらエラーが出てインストールできなかったので，エラーメッセージを見たんですが，本家のほうでリリースされてなかったのが原因と分かるまで少し時間がかかりました。
もし「sass_embedded-1.54.0-macos-arm64.tar.gz が https://github.com/sass/dart-sass-embedded/releases/tag/1.54.0 に無い」ってエラーだったらすぐに理解できたかも，と思ってこの issue を立ててみたんですが，閉じていただいてもいいです。

なお，本家のほうで
https://github.com/sass/dart-sass-embedded/issues/90
こういうやりとりがあったのは，あとで知りました。

**Comment by ntkme** [comment]
報告ありがとうございます。

他の方も同じエラーに遭遇してるかもしれないので、 dart-sass-embedded が修正されるまでこの issue はオーペンのままでいいと思います。

**Comment by ntkme** [comment]
1.54.2 is now available.
