### ISSUE TITLE
Slim requires Sass engine to accept `cache` option

### ISSUE THREAD

**Issue by scivola** [ntkme/sass-embedded-host-ruby#61]
This issue was originally posted as https://github.com/slim-template/slim/issues/889.
But the development of Slim seems to be stagnant.

Is it possible to resolve it by letting [Sass::Embedded#compile_string](https://github.com/ntkme/sass-embedded-host-ruby/blob/v1.54.5/lib/sass/embedded.rb#L187-L205) accept `cache` option (and simply ignore it)?

**Comment by ntkme** [comment]
The major issue is slim appears to be abandoned.

Even if we allow the `cache` option to be ignored, you will hit another issue https://github.com/slim-template/slim/pull/887.

I would recommend just redefining `Slim::Embedded::SassEngine` (plus we can set `charset: false` for inlined `<style>`):

``` ruby
require "bundler"
Bundler.require

# Redefine Slim::Embedded::SassEngine for sass-embedded
module Slim
  class Embedded
    class SassEngine < TiltEngine
      define_options :pretty

      protected

      def tilt_render(tilt_engine, tilt_options, text)
        text = tilt_engine.new(tilt_options.merge(
          style: options[:pretty] ? :expanded : :compressed,
          charset: false # do not emit `@charset` or BOM for <style> 
        )) { text }.render
        [:static, text]
      end
    end
  end
end

template = Slim::Template.new{ <<~SLIM }
  doctype html
  meta charset="utf-8"
  title test sass: in Slim
  sass:
    body
      background: orange
  h1 Hello
SLIM
```

**Comment by ntkme** [comment]
https://github.com/rtomayko/tilt/pull/383

**Comment by scivola** [comment]
Thank you for the advice.

**Comment by ntkme** [comment]
Looks like the upstream has resumed development activity. PR submitted and we will see.

**Comment by ntkme** [comment]
Here is another attempt, we will see how it goes: https://github.com/slim-template/slim/pull/931

**Comment by ntkme** [comment]
Upstream PR is merged. It should work once upstream cut the next release.

**Comment by ntkme** [comment]
It's now supported with `slim >=5.2.0` and `tilt >= 2.0.11`.
