### ISSUE TITLE
Time lag between google-protobuf ruby and maven protoc releases can cause install failures

### ISSUE THREAD

**Issue by chadlwilson** [ntkme/sass-embedded-host-ruby#66]
Not sure there is much that can be done here, however at time of writing `3.21.6` has been pushed to RubyGems (and dependabot suggested an update) yet the same binaries for `com.google.protobuf:protoc:3.21.6` has not been pushed to Maven Central [here](https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.21.6/), causing installs to fail.

https://github.com/ntkme/sass-embedded-host-ruby/blob/b08a6fd547b0660ef2d9dd5133f3f173daf260ec/ext/sass/Rakefile#L245-L246

Feel free to close, since I imagine there is likely not much that can be done about it, but I was a little bit surprised naively to find the install time dependency on Maven Central  :-)

**Comment by chadlwilson** [comment]
Yeah, no release branches either. Maybe the release process broke part way through in a weird way. You'd expect tag first, push packages later though.

Seems a bit of noise at https://github.com/protocolbuffers/protobuf/issues/10562, https://github.com/protocolbuffers/protobuf/issues/10564 etc with other versions also

**Comment by ntkme** [comment]
- https://my.diffend.io/gems/google-protobuf/3.19.4/3.19.5
- https://my.diffend.io/gems/google-protobuf/3.20.1/3.20.2
- https://my.diffend.io/gems/google-protobuf/3.21.5/3.21.6

No change on rubygems... Pypi seems to be broken per your links.

https://github.com/protocolbuffers/protobuf/compare/21.x-202208092202...21.x-202209132118

> C++
> * Reduce memory consumption of MessageSet parsing

So the change should only impact the C++ release. Supposedly it should release all languages at the same time.

**Comment by chadlwilson** [comment]
Yeah. Also https://github.com/protocolbuffers/protobuf/issues/10568

**Comment by ntkme** [comment]
Looks like protoc in maven has been published.
