### ISSUE TITLE
started getting error `that version can no longer be found in that source` error

### ISSUE THREAD

**Issue by kKerem** [ntkme/sass-embedded-host-ruby#88]
after the new release its started to fail in actions. Works fine in local but I can't use the updated version of my jekyll website in my github page anymore.
Any ideas?
```
2022-12-26T11:40:27.7759734Z Your bundle is locked to sass-embedded (1.57.1-x86_64-linux) from rubygems
2022-12-26T11:40:27.7760625Z repository https://rubygems.org/ or installed locally, but that version can no
2022-12-26T11:40:27.7761977Z longer be found in that source. That means the author of sass-embedded
2022-12-26T11:40:27.7762673Z (1.57.1-x86_64-linux) has removed it. You'll need to update your bundle to a
2022-12-26T11:40:27.7763310Z version other than sass-embedded (1.57.1-x86_64-linux) that hasn't been removed
2022-12-26T11:40:27.7763758Z in order to install.
```
https://github.com/kKerem/kkerem.github.io/actions/runs/3781014955

**Comment by ntkme** [comment]
Your `Gemfile.lock` was created with bundler `2.2.27`. Please delete the `Gemfile.lock` and recreate it with bundler `>= 2.3.22` and it should fix the issue as this was actually a bug in rubygems/bundler.

**Comment by frederikspang** [comment]
I'm seeing the same error on latest rubygems/bundler, as well as on 2.3.26.

We have the following platforms in Gemfile.lock

```
PLATFORMS
  arm64-darwin
  ruby
  x86_64-darwin
  x86_64-linux
```

and
```
    sass-embedded (1.57.1-arm64-darwin)
      google-protobuf (~> 3.21)
    sass-embedded (1.57.1-x86_64-darwin)
      google-protobuf (~> 3.21)
    sass-embedded (1.57.1-x86_64-linux)
      google-protobuf (~> 3.21)
```

Seeing the following error in GitHub Actions runs - But not locally on my Mac (arm64-darwin).

```
Your bundle is locked to sass-embedded (1.57.1-arm64-darwin) from rubygems repository https://rubygems.org/ or installed locally, but that version can no longer be found in that source.
That means the author of sass-embedded (1.57.1-arm64-darwin) has removed it. You'll need to update your bundle to a version other than sass-embedded (1.57.1-arm64-darwin) that hasn't been removed in order to install.
```

Can we reopen this issue, as it may not be solved from >= 2.3.22 unless I am missing something.

**Comment by ntkme** [comment]
@frederikspang You need rubygems >=3.3.22 and bundler >=2.3.22. `sass-embedded (1.57.1-x86_64-linux)` in `Gemfile.lock` indicates that it was generated with a broken version of rubygems/bundler. Correct one should look like `sass-embedded (1.57.1-x86_64-linux-gnu)` - with `-gnu` at the end.

**Comment by ntkme** [comment]
This is a sample of a good `Gemfile.lock`:

```
GEM
  remote: https://rubygems.org/
  specs:
    google-protobuf (3.21.12)
    sass-embedded (1.57.1-arm64-darwin)
      google-protobuf (~> 3.21)
    sass-embedded (1.57.1-x86_64-linux-gnu)
      google-protobuf (~> 3.21)

PLATFORMS
  arm64-darwin-22
  x86_64-linux

DEPENDENCIES
  sass-embedded (~> 1.54)

BUNDLED WITH
   2.4.3
```

Please make sure you have rubygems >=3.3.22 and bundler >=2.3.22 all the time.

**Comment by frederikspang** [comment]
@ntkme You were absolutely right.. The workstation that ran the `bundle update` from 1.55.x (I think) to 1.57.1 were created with bundler 2.3.26 - But with a lower version of rubygems. I was fooled by the misleading `BUNDLED WITH` stmt.
