### ISSUE TITLE
Occasional installation failure

### ISSUE THREAD

**Issue by ashmaroli** [ntkme/sass-embedded-host-ruby#89]
I first encountered this issue with a Jekyll plugin repository.
I then tried to reproduce this issue with a fork of `sass-embedded-host-ruby`. I was successful just once among many runs with the trace:

```
  Fetching sass-embedded 1.57.1
  Installing sass-embedded 1.57.1 with native extensions
  Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
  
  current directory:
  /home/runner/work/sass-embedded/sass-embedded/vendor/bundle/ruby/3.0.0/gems/sass-embedded-1.57.1/ext/sass
  /opt/hostedtoolcache/Ruby/3.0.5/x64/bin/ruby
  -I/opt/hostedtoolcache/Ruby/3.0.5/x64/lib/ruby/3.0.0 -rrubygems
  /home/runner/work/sass-embedded/sass-embedded/vendor/bundle/ruby/3.0.0/gems/rake-10.5.0/bin/rake
  RUBYARCHDIR\=/home/runner/work/sass-embedded/sass-embedded/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/sass-embedded-1.57.1
  RUBYLIBDIR\=/home/runner/work/sass-embedded/sass-embedded/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/sass-embedded-1.57.1
  fetch
  https://github.com/sass/dart-sass-embedded/releases/download/1.57.1/sass_embedded-1.57.1-linux-x64.tar.gz
  rake aborted!
  ArgumentError: wrong number of arguments (given 2, expected 1)
  /home/runner/work/sass-embedded/sass-embedded/vendor/bundle/ruby/3.0.0/gems/sass-embedded-1.[57](https://github.com/ashmaroli/sass-embedded/actions/runs/3816688510/jobs/6492472257#step:3:63).1/ext/sass/Rakefile:102:in
  `unarchive'
  /home/runner/work/sass-embedded/sass-embedded/vendor/bundle/ruby/3.0.0/gems/sass-embedded-1.57.1/ext/sass/Rakefile:22:in
  `block in <top (required)>'
  Tasks: TOP => default => install => embedded.rb => sass_embedded
  (See full trace by running task with --trace)
```
The full run is [here](https://github.com/ashmaroli/sass-embedded/actions/runs/3816688510/jobs/6492472409)

Any idea what could be wrong?

**Comment by ntkme** [comment]
Has to do with the specific combination of Ruby and Rake version. Ruby `>=3.0` must use Rake `>=13.0.0`: https://github.com/ruby/rake/commit/baa23cc8a8cc624bc8f46c8a55d2f0caade568ea  

Reason that it does not enforce latest Rake version is that any Rake version that comes with Ruby installation is compatible (Ruby 3.0.0 comes with Rake 13.0.3). Unless user lock Rake to an incorrect version, it should work just fine.

**Comment by ashmaroli** [comment]
I had a hunch, this was somehow related to kw_args but didn't deep.
The Jekyll plugin repository I mentioned has already bumped the Rake version in use.
Good to know that you're aware of the issue.
